[build]
  functions = "netlify/functions"
  command = ""

[functions]
  included_files = ["netlify/functions/requirements.txt"]
  runtime = "python3.13" # 또는 "python3.x" 와 같이 Python 3 버전을 명시할 수 있습니다.
