[build]
  command = "pip install -r netlify/functions/requirements.txt"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/*"]

  [functions.runtime]
    external_node_modules = []
