[build]
  functions = "netlify/functions"
  command = "" # 정적 사이트와 함수만 사용하는 경우 빌드 명령은 필요 없습니다.

[functions]
  included_files = ["netlify/functions/requirements.txt"]
  runtime = "python3.13.2" # 필요에 따라 특정 Python 3 버전 (예: python3.9)을 지정할 수도 있습니다.
